title: Rapid Logix Docs
description: View the docs
theme: just-the-docs
markdown: kramdown

url: https://just-the-docs.github.io
logo: assets/rapid-spray-logo.png

footer_content: "Epic Footer Content"
color_scheme: rapidLogix

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
