title: Rapid Logix Docs
description: View the docs
theme: just-the-docs
markdown: kramdown

url: https://just-the-docs.github.io
logo: assets/rapid-spray-logo.png

color_scheme: custom
heading_anchors: true

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

callouts:
  note:
    title: note
    color: green
  warning:
    title: warning
    color: yellow
  important:
    title: important
    color: red
